package formularios;

import classes.Dados;
import classes.Dados_db;
import classes.Utilidades;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erica
 */
public class frmPesqProduto extends javax.swing.JDialog {

    private Dados msDados;
    private DefaultTableModel mTabela;
    private String resposta = "";

    private Dados_db msDados_db;

    public void setDados_db(Dados_db msDados_db) {
        this.msDados_db = msDados_db;
    }

    public void setDados(Dados msDados) {
        this.msDados = msDados;
    }

    public String getResposta() {
        return resposta;
    }

    private void preencherTabela() {
        String titulos[] = {"ID Produto", "Descrição"};
        String registro[] = new String[2];
        mTabela = new DefaultTableModel(null, titulos);
        String sql = "";
        if (txtPesqProduto.getText().equals("")) {
            sql = "SELECT idProduto, descricao FROM produtos";
        } else {
            if (jRBDescricao.isSelected()) {
                sql = "SELECT idProduto, descricao FROM produtos "
                        + "WHERE descricao LIKE '" + txtPesqProduto.getText() + "%'";
            }
            if (jRBIDProduto.isSelected()) {
                sql = "SELECT idProduto, descricao FROM produtos "
                        + "WHERE idProduto LIKE '" + txtPesqProduto.getText() + "%'";
            }
        }

        ResultSet rs = msDados_db.getConsulta(sql);

        try {
            while (rs.next()) {
                registro[0] = rs.getString("idProduto");
                registro[1] = rs.getString("descricao");
                mTabela.addRow(registro);
            }
            jTabela.setModel(mTabela);
            return;
        } catch (SQLException ex) {
            Logger.getLogger(frmPesqProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }

    public frmPesqProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGTipoPesq = new javax.swing.ButtonGroup();
        btnPesquisarProduto = new javax.swing.JButton();
        btnPesquisarSair = new javax.swing.JButton();
        txtPesqProduto = new javax.swing.JTextField();
        jRBDescricao = new javax.swing.JRadioButton();
        jRBIDProduto = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Produto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pesql.gif"))); // NOI18N
        btnPesquisarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });

        btnPesquisarSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnPesquisarSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarSairActionPerformed(evt);
            }
        });

        txtPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqProdutoActionPerformed(evt);
            }
        });

        bGTipoPesq.add(jRBDescricao);
        jRBDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRBDescricao.setForeground(new java.awt.Color(0, 51, 102));
        jRBDescricao.setText("Descrição");
        jRBDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBDescricaoActionPerformed(evt);
            }
        });

        bGTipoPesq.add(jRBIDProduto);
        jRBIDProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRBIDProduto.setForeground(new java.awt.Color(0, 51, 102));
        jRBIDProduto.setSelected(true);
        jRBIDProduto.setText("ID Produto");
        jRBIDProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBIDProdutoActionPerformed(evt);
            }
        });

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisarSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPesqProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRBIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRBDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBIDProduto)
                    .addComponent(jRBDescricao))
                .addGap(18, 18, 18)
                .addComponent(txtPesqProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisarSair, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
        int num = jTabela.getRowCount();
        if (num == 0) {
            resposta = "";
            dispose();
            return;
        }
        for (int i = 0; i < num; i++) {
            if (jTabela.isRowSelected(i)) {
                resposta = Utilidades.objectToString(jTabela.getValueAt(i, 0));
                dispose();
                return;
            }
        }
        resposta = Utilidades.objectToString(jTabela.getValueAt(0, 0));
        dispose();
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void btnPesquisarSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarSairActionPerformed
        resposta = "";
        dispose();
    }//GEN-LAST:event_btnPesquisarSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        preencherTabela();
        txtPesqProduto.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void jRBIDProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBIDProdutoActionPerformed
        txtPesqProduto.setText("");
        txtPesqProduto.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_jRBIDProdutoActionPerformed

    private void jRBDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBDescricaoActionPerformed
        txtPesqProduto.setText("");
        txtPesqProduto.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_jRBDescricaoActionPerformed

    private void txtPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqProdutoActionPerformed
        preencherTabela();
    }//GEN-LAST:event_txtPesqProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPesqProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPesqProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPesqProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPesqProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPesqProduto dialog = new frmPesqProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGTipoPesq;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JButton btnPesquisarSair;
    private javax.swing.JRadioButton jRBDescricao;
    private javax.swing.JRadioButton jRBIDProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JTextField txtPesqProduto;
    // End of variables declaration//GEN-END:variables
}
