package formularios;

import classes.Dados_db;

/**
 *
 * @author Erica
 */
public class frmRelatoriosVendas extends javax.swing.JInternalFrame {

    private Dados_db msDados_db;

    public void setDados_db(Dados_db msDados_db) {
        this.msDados_db = msDados_db;
    }
    
    public frmRelatoriosVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGRFiltro = new javax.swing.ButtonGroup();
        bGRTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtArquivo = new javax.swing.JTextField();
        btnSelecao = new javax.swing.JButton();
        jRData = new javax.swing.JRadioButton();
        jRCliente = new javax.swing.JRadioButton();
        jRNumVenda = new javax.swing.JRadioButton();
        jRTodos = new javax.swing.JRadioButton();
        jRSelecao = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Relatório de vendas:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Arquivo:");

        btnSelecao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSelecao.setForeground(new java.awt.Color(0, 51, 102));
        btnSelecao.setText("...");

        bGRFiltro.add(jRData);
        jRData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRData.setSelected(true);
        jRData.setText("Data Venda");

        bGRFiltro.add(jRCliente);
        jRCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRCliente.setText("Cliente");

        bGRFiltro.add(jRNumVenda);
        jRNumVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRNumVenda.setText("Número Venda");

        bGRTipo.add(jRTodos);
        jRTodos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRTodos.setSelected(true);
        jRTodos.setText("Todas Venda");

        bGRTipo.add(jRSelecao);
        jRSelecao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRSelecao.setText("Seleção Venda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRSelecao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRData)
                        .addGap(18, 18, 18)
                        .addComponent(jRNumVenda)
                        .addGap(18, 18, 18)
                        .addComponent(jRCliente)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecao))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTodos)
                    .addComponent(jRSelecao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRData)
                    .addComponent(jRNumVenda)
                    .addComponent(jRCliente))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        setBounds(500, 200, 617, 414);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGRFiltro;
    private javax.swing.ButtonGroup bGRTipo;
    private javax.swing.JButton btnSelecao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRCliente;
    private javax.swing.JRadioButton jRData;
    private javax.swing.JRadioButton jRNumVenda;
    private javax.swing.JRadioButton jRSelecao;
    private javax.swing.JRadioButton jRTodos;
    private javax.swing.JTextField txtArquivo;
    // End of variables declaration//GEN-END:variables
}
